### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by tanimutomo** [tanimutomo/clean-architecture-api-go#1]
- [x] Add db AutoMigrate
- [x] Reject a request to add the same name tag to one article
- [x] Move interfaces from service layer to repository implementation layer
